[color-pallete]
black = "#282a36" 
white = "#f8f8f2" 
green = "#50fa7b"
red = "#ff5555"
orange = "#ffb86c"
yellow = "#f1fa8c"
purple = "#bd93f9"
cyan = "#8be9fd"
grey = "#6272a4"
light_grey = "#44475a"

